# Copyright 2019-2022 Tauri Programme within The Commons Conservancy
# SPDX-License-Identifier: Apache-2.0
# SPDX-License-Identifier: MIT

name = "tauri-schema"
main = "build/worker/shim.mjs"
compatibility_date = "2023-08-23"
send_metrics = false

# The minor version of worker-build must match worker/worker-macros in Cargo.toml!
[build]
command = "cargo install -q worker-build@^0.7 && worker-build --release"

[observability]
enabled = true
head_sampling_rate = 1
